name: Generate Doxygen Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate docs
      run: doxygen Doxyfile

    - name: (Optional) Push docs to a branch or another location
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Generated Doxygen docs"
        git push
